---
language: php
php:
  - '7.3'
  - '7.4'
  # - hhvm # on Trusty only (new/current default is Bionic, ie. "dist: bionic")
  # - nightly # nightly is now v. 8.0.0-dev; no version of phpunit accepts anything above ^7
install:
  - composer install --no-interaction --prefer-source
before_script:
  - npm install -g grunt-cli
  - npm install
script:
  - bash tests/lint.sh
  - vendor/bin/phpunit tests
  - grunt travis -v
  - vendor/phploc/phploc/phploc src
